version: "3.8"

services:
  app:
    container_name: app-dev
    image: app-dev
    env_file:
      - .env
    build:
      context: ../
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8080:3000
